-- Write a SQL query to retrieve the total revenue generated by each product category.
-- Display the category name along with the total revenue in descending order of the revenue.
-- categories = c, orders = o, order_items = oi, products = p
SELECT c.name, SUM(p.price * oi.quantity) AS total_revenue
FROM categories c
         LEFT JOIN products p ON c.id = p.category_id
         LEFT JOIN order_items oi ON p.id = oi.product_id
         LEFT JOIN orders o ON oi.order_id = o.id
GROUP BY c.id, c.name
ORDER BY total_revenue DESC;